[workspace]
members = [
    "crates/rivet-core",
    "crates/rivet-python",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
arrow = "59.3.0"
arrow-ipc = "59.3.0"
image = "0.25.10"
numpy = "0.29.0"
pyo3 = "0.29.0"
rivet-core = { path = "crates/rivet-core" }
thiserror = "2.0.17"
