[package]
name = "rivet-dataset"
version.workspace = true
edition.workspace = true

[dependencies]
arrow.workspace = true
arrow-array.workspace = true
arrow-buffer.workspace = true
arrow-ipc.workspace = true
bytes.workspace = true
crossbeam-channel.workspace = true
futures.workspace = true
image.workspace = true
lance.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
walkdir.workspace = true
memmap2.workspace = true
